options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/notes-backend', './backend']
  
  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/notes-backend']
  
  # Build frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/notes-frontend', './frontend']
    id: build-frontend
  
  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/notes-frontend']
    waitFor: ['build-frontend']
  
  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'notes-backend', 
           '--image', 'gcr.io/$PROJECT_ID/notes-backend',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--port', '8080',  # Tambahkan ini
           '--allow-unauthenticated',
           '--set-env-vars', 'DB_HOST=your-cloud-sql-ip',
           '--set-env-vars', 'DB_USER=root',
           '--set-env-vars', 'DB_PASSWORD=secret',
           '--set-env-vars', 'DB_NAME=notes_app',
           '--set-env-vars', 'JWT_SECRET=your_jwt_secret']
           '--timeout', '300s',  # Timeout 5 menit
           '--max-instances', '1'  # Batasi instance untuk development
  
  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'notes-frontend', 
           '--image', 'gcr.io/$PROJECT_ID/notes-frontend',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']
           '--timeout', '300s',  # Timeout 5 menit
           '--max-instances', '1'  # Batasi instance untuk development

    # Set IAM Policy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args: 
      - '-c'
      - |
        gcloud beta run services add-iam-policy-binding notes-backend \
          --region=us-central1 \
          --member=allUsers \
          --role=roles/run.invoker

images:
  - 'gcr.io/$PROJECT_ID/notes-backend'
  - 'gcr.io/$PROJECT_ID/notes-frontend'
