options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/notes-backend', './backend']
  
  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/notes-backend']
  
  # Build frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/notes-frontend', './frontend']
    id: build-frontend
  
  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/notes-frontend']
    waitFor: ['build-frontend']
  
  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'notes-backend', 
           '--image', 'gcr.io/$PROJECT_ID/notes-backend',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']
  
  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'notes-frontend', 
           '--image', 'gcr.io/$PROJECT_ID/notes-frontend',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/notes-backend'
  - 'gcr.io/$PROJECT_ID/notes-frontend'
